fix latteart-org/latteart#21 added screenshots dl
latteart-org/latteart-repository pull request #28
Opened 2022-06-07 01:02 UTC by mamoru-x-yanagisawa

Signed-off-by: Mamoru Yanagisawa <72236660+mamoru-x-yanagisawa@users.noreply.github.com>

2022-06-07 06:55 UTC, fujiwr requested changes

2022-06-07 06:55 UTC, fujiwr commented on src/ServerError.ts
> +  GET_SCREENSHOTS = "get_screenshots_failed",
他と合わせて`GET_SCREENSHOTS_FAILED`としてください。

2022-06-07 06:55 UTC, fujiwr commented on src/services/StaticDirectoryService.ts
> + * Copyright 2021 NTT Corporation.
2021になっています。

2022-06-07 06:55 UTC, fujiwr commented on src/services/ScreenshotsService.ts
> + * Copyright 2021 NTT Corporation.
2021になっています。

2022-06-07 06:55 UTC, fujiwr commented on src/controllers/ScreenshotsController.ts
> + * Copyright 2021 NTT Corporation.
2021になっています。

2022-06-07 06:55 UTC, fujiwr commented on tests/helper/createServiceMock.ts
> + * Copyright 2021 NTT Corporation.
2021になっています。

2022-06-07 08:06 UTC, mamoru-x-yanagisawa commented on src/ServerError.ts
> +  GET_SCREENSHOTS = "get_screenshots_failed",
ご指摘の通り修正致しました

2022-06-07 08:07 UTC, mamoru-x-yanagisawa commented on src/services/StaticDirectoryService.ts
> + * Copyright 2021 NTT Corporation.
ご指摘の通り修正致しました

2022-06-07 08:08 UTC, mamoru-x-yanagisawa commented on tests/helper/createServiceMock.ts
> + * Copyright 2021 NTT Corporation.
ご指摘の通り修正致しました

2022-06-08 02:25 UTC, fujiwr approved these changes

2022-06-08 02:34 UTC, merged